name: flutter_i18n_example
description: Demonstrates how to use the flutter_i18n plugin.

publish_to: 'none'

environment:
  sdk: ">=2.12.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_i18n:
    path: ../
  cupertino_icons: ^1.0.2
  http:
  path_provider:

dev_dependencies:
#  flutter_test:
#    sdk: flutter
#  integration_test: ^1.0.2+3
#  test: any

flutter:
  uses-material-design: true
  assets:
    - assets/i18n/
    - assets/i18n_namespace/en/
    - assets/i18n_namespace/ua/